### ISSUE TITLE
It can't find the language model

### ISSUE THREAD

**Issue by Derrick2217** [Anil-matcha/ChatPDF#20]
C:\Users\Rose\chatWeb>python main.py
Traceback (most recent call last):
  File "C:\Users\Rose\chatWeb\main.py", line 4, in <module>
    from api import api
  File "C:\Users\Rose\chatWeb\api.py", line 15, in <module>
    from contents import web_crawler_newspaper, extract_text_from_txt, extract_text_from_docx, \
  File "C:\Users\Rose\chatWeb\contents.py", line 7, in <module>
    from langdetect import detect
ModuleNotFoundError: No module named 'langdetect'

**Comment by RJS32** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
